// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GavelPoMobile.SandBox3.Models;

public partial class VPoApprover
{
    public Guid Oid { get; set; }

    public string No { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Popassword { get; set; }
}