// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GavelPoMobile.SandBox.Models
{
    public partial class GetPODetailsByIdResult
    {
        public int OID { get; set; }
        public string SourceNo { get; set; }
        public int? GenJournalID { get; set; }
        public string Description { get; set; }
        public decimal? Quantity { get; set; }
        public string UOM { get; set; }
        public decimal? Cost { get; set; }
        public string CostCenter { get; set; }
        public string RequestedBy { get; set; }
        public decimal? Total { get; set; }
        public int? LineApprovalStatus { get; set; }
        public string Remarks { get; set; }
    }
}
