// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using GavelPoMobile.SandBox.Models;
using Microsoft.EntityFrameworkCore;

namespace GavelPoMobile.SandBox.Data;

public partial class GVLLOCALContext : DbContext
{
    public GVLLOCALContext()
    {
    }

    public GVLLOCALContext(DbContextOptions<GVLLOCALContext> options)
        : base(options)
    {
        this.Database.SetCommandTimeout(TimeSpan.FromMinutes(5));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}