// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GavelPoMobile.SandBox.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace GavelPoMobile.SandBox.Data
{
    public partial interface IGVLLOCALContextProcedures
    {
        Task<List<GetOrderByIdResult>> GetOrderByIdAsync(int? orderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<GetOrdersResponse> GetOrdersAsync(int? page, int? pageSize, CancellationToken cancellationToken = default);
        Task<GetOrdersInfiniteResponse> GetOrdersInfiniteAsync(int? status, int? page, int? pageSize, CancellationToken cancellationToken = default);
        Task<GetOrdersPaginationResponse> GetOrdersPaginationAsync(int? status, int? page, int? pageSize, CancellationToken cancellationToken = default);
        Task<List<GetPODetailsByIdResult>> GetPODetailsByIdAsync(int? genJournalId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<GetPOPastApprovalsResponse> GetPOPastApprovalsAsync(int? page, int? pageSize, CancellationToken cancellationToken = default);
    }
}
