// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using GavelPoMobile.SandBox3.Models;
using Microsoft.EntityFrameworkCore;

namespace GavelPoMobile.SandBox3.Data;

public partial class GVLLOCALContext : DbContext
{
    public GVLLOCALContext()
    {
    }

    public GVLLOCALContext(DbContextOptions<GVLLOCALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VPoApprover> VPoApprover { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=(local);Initial Catalog=GVLLOCAL;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<VPoApprover>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vPoApprover");

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.No).HasMaxLength(100);
            entity.Property(e => e.Popassword)
                .HasMaxLength(100)
                .HasColumnName("POPassword");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}