// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using GavelPoMobile.SandBox3.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace GavelPoMobile.SandBox3.Data
{
    public partial interface IGVLLOCALContextProcedures
    {
        Task<int> UpdatePOLineStatusAsync(int? Oid, int? Status, string Remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdatePurchaseOrderStatusAsync(int? Oid, int? Status, string Remarks, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
